[project]
name = "cutler"
version = "0.1.0"
description = "Cut and concat videos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["click", "py-nickel", "ffmpeg-python", "rich"]

[project.scripts]
cutler = "cutler.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cutler"]

[tool.ruff]
line-length = 100
